version: '3.8'
services:
  # データベースサーバーの設定
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mysns
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

# データを永続化するための保存領域
volumes:
  db-data: